name: Release Workflow to Deploy to ACR

on:
  release:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: read

env:
  VERSION_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DEFAULT_REGISTRY_SERVER }}
          username: ${{ secrets.DEFAULT_REGISTRY_USERNAME }}
          password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}

      - name: ğŸ“¤ Build and push container image to registry (Frontend)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundiacfe:${{ env.VERSION_TAG }}
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundiacfe:latest
          file: ./frontend/Dockerfile
          context: ./frontend
      
      - name: ğŸ“¤ Build and push container image to registry (Backend)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundiacms:${{ env.VERSION_TAG }}
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundiacms:latest
          file: ./backend/Dockerfile
          context: ./backend